[package]
name = "contract"
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
version = "0.3.0"
=======
version = "0.2.0"
>>>>>>> c2e1d85 (Addressing minor issues. Introducting state migration for upgrades)
=======
version = "0.3.0"
>>>>>>> 899b7fd (Fix farm claim all, add potential farms into the account view, xBooster token)
=======
version = "0.2.0"
>>>>>>> 9f1cff0 (Addressing minor issues. Introducting state migration for upgrades)
=======
version = "0.3.0"
>>>>>>> c3b16a5 (Fix farm claim all, add potential farms into the account view, xBooster token)
=======
version = "0.4.0"
>>>>>>> b9665e0 (Add remote upgrade functionality by owner)
authors = ["Eugene The Dream <ek@proximity.dev>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "=4.0.0-pre.7"
near-contract-standards = "=4.0.0-pre.7"
near-sys = "=0.1"
uint = { version = "=0.9.0", default-features = false }
common = { path = "../common/" }
once_cell = "=1.8.0"

[dev-dependencies]
rand = "0.8"
